### PR TITLE
convert key to base64 notation before storing

### PR DESCRIPTION
**Pull request by thomasdelaet**
if a key value contains /, error is generated while trying to store the file

this PR converst a key to base64 notation before storing the file in the filesystem

### CODE REVIEW

**Comment by bookchin** [comment]
Thanks, can you bump the package version to 0.1.0 to indicate backwards incompatibility?

**Comment by thomasdelaet** [comment]
done

**Comment by thomasdelaet** [comment]
Any chance this one can get merged? Thanks

**Comment by bookchin** [comment]
Yes sorry, will do shortly.

**Comment by bookchin** [comment]
Will tag and publish as well and eventually update kad's pointer.

**Pull request merged**
